# Generated by Django 4.1.3 on 2022-12-23 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_thread_thread_likes_user_institution_user_major_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
