# Generated by Django 4.1.3 on 2022-12-24 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetopic',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursetopic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='deadline',
            name='course',
        ),
        migrations.RemoveField(
            model_name='deadline',
            name='user',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='course',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='thread_author',
        ),
        migrations.RemoveField(
            model_name='threadlike',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='threadlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CourseTopic',
        ),
        migrations.DeleteModel(
            name='Deadline',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
        migrations.DeleteModel(
            name='ThreadLike',
        ),
    ]
